/* @flow */

const actionTypes = {
	ADD_TODO: 'ADD_TODO',
	DELETE_TODO: 'DELETE_TODO',
	EDIT_TODO: 'EDIT_TODO',
	TOGGLE_TODO: 'TOGGLE_TODO',
	COMPLETE_ALL: 'COMPLETE_ALL',
	CLEAR_COMPLETED: 'CLEAR_COMPLETED',
};

export default actionTypes;
